/**
 * motor.c
 *
 * Created on: July 25, 2026
 *     Author: Dmitry Murashov
 */


/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/****************************************************************************
 * Included files
 ****************************************************************************/

#include "config.h"
#include "motor.h"
#include <stm32f0xx_hal.h>
#include <stm32f0xx_hal_exti.h>
#include <stm32f0xx_ll_exti.h>
#include <stm32f0xx_ll_gpio.h>
#include <stdint.h>

/****************************************************************************
 * Private Types
 ****************************************************************************/

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

/****************************************************************************
 * Private Data
 ****************************************************************************/

static int32_t sEps[2] = {0};
static int sIEp = 0;
static int sEpContact = 0xff;

/* 12-bit ADC (4096), 3.3V rail voltage, 1.65 Hall sensor's value when no flux */
static const int32_t sMeanAdc = 2048;
static const int32_t sMarginAdc = (int32_t)(0.3f / 3.3f * 4096.0f);

/****************************************************************************
 * Public Data
 ****************************************************************************/

/** From autogenerated Cube code */
extern ADC_HandleTypeDef hadc;

/****************************************************************************
 * Private Functions
 ****************************************************************************/

void epsPush(uint32_t aValue)
{
	sEps[sIEp] = aValue;
	sIEp = !sIEp;
}

void epsDetectContact(int32_t aValue)
{
	if (((aValue - sMeanAdc) & 0x7fffffff /* 32-bit abs() */) >= sMarginAdc)
	{
		sEpContact = sIEp;
	}
}

void MOTOR_HALL_EP_ADC_HANDLER(void)
{
	volatile uint32_t isr = hadc.Instance->ISR;
	if (isr & (ADC_ISR_EOC | ADC_ISR_EOSEQ))
	{
		int32_t val = (int32_t)hadc.Instance->DR;
		/* End of conversion. Push the next value */
		epsDetectContact(val);
		epsPush(val);
		hadc.Instance->ISR |= (ADC_ISR_EOC | ADC_ISR_EOSEQ);
	}
	if (isr & ADC_ISR_OVR)
	{
		/* XXX An overrun should never happen. If it has, a conversion has been
		 * missed, so we should wait for the next EOSEQ, to reset the FIFO
		 * counter, and start over from 0th element */
	}
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

int motorIsEp1Contact(void)
{
	if (sEpContact == DirEp1)
	{
		sEpContact = 0xff;
		return 1;
	}
	return 0;
}

int motorIsEp2Contact(void)
{
	if (sEpContact == DirEp2)
	{
		sEpContact = 0xff;
		return 1;
	}
	return 0;
}

void motorSetDir(int dir)
{
	switch (dir)
	{
		case DirEp1:
		{
			LL_GPIO_SetOutputPin(MOTOR_DIR_1_PORT, MOTOR_DIR_1_PIN);
			LL_GPIO_ResetOutputPin(MOTOR_DIR_2_PORT, MOTOR_DIR_2_PIN);
			break;
		}
		case DirEp2:
		default:
		{
			LL_GPIO_ResetOutputPin(MOTOR_DIR_1_PORT, MOTOR_DIR_1_PIN);
			LL_GPIO_SetOutputPin(MOTOR_DIR_2_PORT, MOTOR_DIR_2_PIN);
			break;
		}
	}
}

void motorInit(void)
{
	MOTOR_DIR_CLK_ENABLE();

	GPIO_InitTypeDef init;

	init.Pin = MOTOR_DIR_1_PIN;
	init.Mode = GPIO_MODE_OUTPUT_PP;
	init.Pull = GPIO_NOPULL;
	init.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(MOTOR_DIR_1_PORT, &init);

	init.Pin = MOTOR_DIR_2_PIN;
	init.Mode = GPIO_MODE_OUTPUT_PP;
	init.Pull = GPIO_NOPULL;
	init.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(MOTOR_DIR_2_PORT, &init);

}